apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-zbvn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-zbvn
    app.kubernetes.io/part-of: test-app-fhky
  name: test-component-zbvn
  namespace: build-e2e-hacbs-wkgk
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component-zbvn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component-zbvn
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images:35c2e6d6a34d4b75a1b2313883cf80b7
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources: {}
status: {}
